### ISSUE TITLE
About process custom datasets

### ISSUE THREAD

**Issue by ywaison** [yuqunw/monopatch_nerf#2]
Thank you for sharing the great work, but I had the following difficulties when working with custom datasets. The command line is ：python scripts/preprocess_eth3d.py -i data/horse -o output/horse -s data/horse/sparse/0
![UD$S{E9UBFX}B(X@AT%N49T](https://github.com/yuqunw/monopatch_nerf/assets/138007686/b5fc9bfe-a730-41b7-af48-0a2e13bc1241)

Hope to get your prompt reply, thank you！

**Comment by yuqunw** [comment]
Hi, thank you for your interest in the work. Based on the error message, it's probably because it fails to download the pretrained weight of preprocessing modules. Could you try to change the Internet, or download it manually and place it locally?

**Comment by ywaison** [comment]
> Hi, thank you for your interest in the work. Based on the error message, it's probably because it fails to download the pretrained weight of preprocessing modules. Could you try to change the Internet, or download it manually and place it locally?

Thank you for your timely reply. I would like to know where I can go to the pre-training weights or do you provide a link? Thank you again!

**Comment by yuqunw** [comment]
Hi, I am not fully sure which model you fail to download, but you might want to locate it and find the link for the model weight in the specific installation file, i.e., the google drive id of https://github.com/leejaeyong7/OmnidataModels/blob/main/omnidata/dpt_depth.py or the downloading link in https://github.com/leejaeyong7/ADE20KSegmenter/blob/main/ade20k_segmenter/segmentation_module.py. Thanks!
